# Generated by Django 4.2.3 on 2023-07-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dep',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
