# Generated by Django 4.2.3 on 2023-07-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_doctor_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('booked', models.DateField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor')),
            ],
        ),
    ]
